### PR TITLE
Mariana new files

### PR DESCRIPTION
**Pull request by ma-oliveiramarques**
I did one .js file for each theme. I couldn't run it on node...

### CODE REVIEW

**Review by pncsoares — APPROVED** [review]

**Comment by pncsoares** [comment]
> I did one .js file for each theme. I couldn't run it on node...

What was the error?

**Comment by pncsoares** [comment]
Ok, I already saw why you couldn't run the code using node.
It was because you were using `document.write` and as I told you yesterday, you must use `console.log` when you're trying to run the javascript code using node.
See my last commit and you'll understand what I'm saying.

**Comment by pncsoares** [comment]
@ma-oliveiramarques let me know if you disagree or if you have a different opinion 😉

**Comment by ma-oliveiramarques** [comment]
Thank you so much for your help @pncsoares !! I saw your corrections :)
I think the problem in that day was also me not knowing how to run node... Now you already taught me, so I need to try it again.

**Pull request merged**
